### ISSUE TITLE
Disable cache doesn't work

### ISSUE THREAD

**Issue by RonaldKools** [cvc-digital/typo3-twig#57]
When disabling the cache, templates are still being cached using the CVC Twig plugin. To disable cache I used the NullBackend:

foreach ($GLOBALS['TYPO3_CONF_VARS']['SYS']['caching']['cacheConfigurations'] as $cacheName => $cacheConfiguration) {
        $GLOBALS['TYPO3_CONF_VARS']['SYS']['caching']['cacheConfigurations'][$cacheName]['backend'] = \TYPO3\CMS\Core\Cache\Backend\NullBackend::class;
        $GLOBALS['TYPO3_CONF_VARS']['SYS']['caching']['cacheConfigurations'][$cacheName]['options']['defaultLifetime'] = 0;
}

This way, using FLUIDTEMPLATE the template cache is disabled too, so any changes in frontend templates are visible immediately. With TWIGTEMPLATE however you need to clear the cache ("Flush all caches") after every adjustment to see your changes. 

This might be caused by the deprecation issues from Typo v9.0 that have been removed in v10.0 but still exists in the cvc_twig extension:

Classes/DependencyInjection/TwigEnvironmentCompilerPass.php Fetch of property "debug"
42: $this->debug = $debug;
9.0 Deprecation: #83273 - Public properties of TemplateService
10.0 Breaking: #87193 - Deprecated functionality removed

Classes/DependencyInjection/TwigEnvironmentCompilerPass.php Fetch of property "debug"
60: $container->setParameter('twig.debug', $this->debug);
9.0 Deprecation: #83273 - Public properties of TemplateService
10.0 Breaking: #87193 - Deprecated functionality removed

$GLOBALS["TYPO3_CONF_VARS"]["FE"]["debug"] is set to true, but when inspecting the TwigEnvironment debug is set to false. This also causes dump() not to function at all.

Tested in Typo3 v10.4.14

**Comment by markuspoerschke** [comment]
Hello @RonaldKools,

thanks for your report.

> This might be caused by the deprecation issues from Typo v9.0 that have been removed in v10.0 but still exists in the cvc_twig extension:

The mentioned deprecation messages are false positives. The property `$debug` belongs to the class `\Cvc\Typo3\CvcTwig\DependencyInjection\TwigEnvironmentCompilerPass` which is user land and is not affected by changes of the TYPO3 classes.

> $GLOBALS["TYPO3_CONF_VARS"]["FE"]["debug"] is set to true, but when inspecting the TwigEnvironment debug is set to false. This also causes dump() not to function at all.

I was only partially able to reproduce this behavior:

1. I go to the _TYPO3 Installation ➔ Settings ➔ Presets ➔ Debug Settings_, there I select "Live"
2. Clear all caches
3. Visit FE page and reload the page. The cache is active and no Twig template change will have effect
4. I go to the _TYPO3 Installation ➔ Settings ➔ Presets ➔ Debug Settings_, there I select "Debug"
5. Visit FE page and reload the page. The cache is active and no Twig template change will have effect
6. Then the template changes have no effect as well

But clearing the cache once after step 4.) resolves the problem. The problem is that the debug setting is only written into the dependency injection container on compile time. Therefore after changing `$GLOBALS["TYPO3_CONF_VARS"]["FE"]["debug"]` the cache must be cleared completely.

I don't consider the need of clearing the cache after changes to the LocalConfiguration as a bug.

Can you confirm that clearing cache once resolves the problem?

**Comment by RonaldKools** [comment]
Hi @markuspoerschke clearing the cache unfortunately had no effect.

Debug is set to active as described above and I disabled the cache.
All caches are cleared. 

After that, I need to clear the cache after every change in the template itself. So in your reproduction I would add:

7. Do a new Twig template change & reload the page. Changes are not shown as the cache is active, even though we are in debug mode and caches are disabled manually
8. Clear the cache and changes are visible

When I switch back to Fluid and do the same thing I see my changes right away without any need to clear the cache after every template change. Maybe this is intended behaviour, but in that case I prefer the Fluid way. ;-)  

$GLOBALS["TYPO3_CONF_VARS"]["FE"]["debug"] is set to true when I put a breakpoint at the first line of 
` public static function dump()` (on the IF statement). However $env->isDebug() still returns false. This causes the dump() function not to work as you are returned from the method right away.

**Comment by markuspoerschke** [comment]
I added a debug output after https://github.com/cvc-digital/typo3-twig/blob/master/Classes/Mvc/View/StandaloneView.php#L77 that was outputting the debug status of the twig environment: `$this->environment->isDebug()`. It showed that it was active.

The remaining possibility I see where the problem is caused is where the debug is activated. Where do you set `$GLOBALS["TYPO3_CONF_VARS"]["FE"]["debug"]`?

**Comment by RonaldKools** [comment]
Both the FE and BE debug are set in the LocalConfiguration. When debugging using Xdebug I can see they are set, so that looks fine.

**Comment by markuspoerschke** [comment]
I also changed the settings in LocalConfiguration.

Unfortunately I don't use TYPO3 anymore and therefore I can't refer to a real project to test. Time wise I could only review and merge a pull request for this problem.

**Comment by marclindemann** [comment]
Hi @RonaldKools,
we cannot reproduce it, if i am logged in in backend it works as excecpted. 
currently we releasing V11 Version soon, maybe it is possible to reproduce it here. i will close the ticket unless we get more information
